version: '3.8'

services:

  module:
    build:
      context: .
    environment:
      CONFIG_PATH: /module/config.json
    # networks:
    #   - smad-modules-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # - ./data:/data
      - ../../smad-3/data:/data
      - ./config.json:/module/config.json

# networks:
#   smad-modules-net:
#     driver: bridge
